_target_:  src.model.VQADeepSeek
model_path: weights/DeepseekVL-7b/
torch_dtype: bfloat16
max_context_length: 1024
device: auto
trainable: frozen
generate_config:
    type: GenerationConfig
    return_full_text: false
    use_cache: true
    bos_token_id: 100000
    do_sample: false
    eos_token_id: 100001
    pad_token_id: 100001
    # temperature: 0.6
    # top_p: 0.9
    max_new_tokens: 256
