model:
    _target_:  src.model.LlaVA
    model_path: /data3/tangpeiyuan/LLM/weights/llava-1.5-7B/
    torch_dtype: float16
    device: cuda
    # trainable: frozen
    assistant_tag: "ASSISTANT:"
    text_image_processor:
        _target_: src.processor.TextImagePreprocessor
        # system_prompt = "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.",
        system_prompt: "A chat between a curious user and an artificial intelligence assistant. The assistant gives  helpful, detailed, and polite answers to the user's questions."
        chat_template:
            - role: system
              content:
                - type: text
                  text: ""
            - role: user
              content:
                - type: image
                  image: "path/to/image_or_base64"  
                - type: text
                  text: ""
            - role: assistant
              content:
                - type: text
                  text: ""
    generate_config:
        type: GenerationConfig
        return_full_text: false
        use_cache: true
        bos_token_id: 1
        do_sample: false
        eos_token_id: 2
        pad_token_id: 32001
        # temperature: 0.6
        # top_p: 0.9
        max_new_tokens: 256
