
_target_: src.dataset.DPO_Dataset
safety_data:
    _target_: src.dataset.SPA_VL
    data_path: data/SPA_VL/
    split: train
    question: question
    answer: chosen
    image_PATH: image_name
    image: image
    safe: false
    sample: 256
    seed: 0
    
utility_data:
    _target_: src.dataset.VLSafe
    data_path: data/VLSafe_normal
    data_files: helpful_sampled.jsonl  # test dataset
    split: train
    image: image_id
    COCO_img_path: data/VLSafe/images
    safe: True
    sample: 256
    seed: 0