
_target_: src.dataset.PGDAttackDataset
adv_img_folder: data/PGD_attack/Llava/eps_64/
text_dataset:
    _target_: src.dataset.BaseDataset # AdvBench
    data_path: data/AdvBench
    data_files: test.csv
    split: train
    question: goal
    answer: target
    safe: false
    # sample: 32
    seed: 0

    