_target_: src.dataset.SPA_VL
data_path: data/SPA_VL/
# split: train
split: test
question: question
chosen: chosen
image_PATH: image_name
image: image
safe: false
test_data_type: harm
# test_data_type: help
# sample: 32
seed: 0